#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 800

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define BALL_SPEED 2
#define TURN_AMOUNT 1

#define PLAYER_START_X 150
#define PLAYER_START_Y 230

#endif